sedc/home/urls.py
from django.conf.urls import url
from django.urls import reverse_lazy
from home.views import HomePageView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import(
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

urlpatterns = [
    url(r'^$', HomePageView.as_view(), name='home'),
    #url(r'^$', LoginView.as_view(), name='login'),
    url(r'^login/$', LoginView.as_view(template_name='home/login.html'), name='login'),
    url(r'^logout/$', LogoutView.as_view(next_page=reverse_lazy('login')), name='logout')
]

sedc/sedc/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #url(r'^$', TemplateView.as_view(template_name="home.html")),
    url(r'^',include('home.urls',namespace='home')),
    url(r'^',include('reportes.urls',namespace='reportes')),
    url(r'^',include('datalogger.urls',namespace='datalogger')),
    url(r'^',include('estacion.urls',namespace='estacion')),
    url(r'^',include('variable.urls',namespace='variable')),
    url(r'^',include('formato.urls',namespace='formato')),
    url(r'^',include('medicion.urls',namespace='medicion')),
    url(r'^',include('vacios.urls',namespace='vacios')),
    url(r'^',include('frecuencia.urls',namespace='frecuencia')),
    url(r'^',include('importacion.urls',namespace='importacion')),
    url(r'^',include('marca.urls',namespace='marca')),
    url(r'^',include('validacion.urls',namespace='validacion')),
    url(r'^',include('anuarios.urls',namespace='anuarios')),
    url(r'^',include('sensor.urls',namespace='sensor')),
    url(r'^',include('instalacion.urls',namespace='instalacion')),
    url(r'^',include('bitacora.urls',namespace='bitacora')),
    url(r'^',include('cruce.urls',namespace='cruce')),
    url(r'^',include('registro.urls',namespace='registro')),
    url('^', include('django.contrib.auth.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sedc/variable/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns=[
    url(r'^variable/$',views.VariableList.as_view(),name='variable_index'),
    url(r'variable/create/$', views.VariableCreate.as_view(), name='variable_create'),
    url(r'variable/detail/(?P<pk>[0-9]+)/$', views.VariableDetail.as_view(), name='variable_detail'),
    url(r'variable/(?P<pk>[0-9]+)/$', views.VariableUpdate.as_view(), name='variable_update'),
    url(r'variable/(?P<pk>[0-9]+)/delete/$', views.VariableDelete.as_view(), name='variable_delete'),

    url(r'^unidad/$',views.UnidadList.as_view(),name='unidad_index'),
    url(r'unidad/create/$', views.UnidadCreate.as_view(), name='unidad_create'),
    url(r'unidad/detail/(?P<pk>[0-9]+)/$', views.UnidadDetail.as_view(), name='unidad_detail'),
    url(r'unidad/(?P<pk>[0-9]+)/$', views.UnidadUpdate.as_view(), name='unidad_update'),
    url(r'unidad/(?P<pk>[0-9]+)/delete/$', views.UnidadDelete.as_view(), name='unidad_delete'),

    url(r'control/$',views.ControlList.as_view(),name='control_index'),
    url(r'control/(?P<page>[0-9]+)/$',views.ControlList.as_view(),name='control_index'),
    url(r'control/create/$', views.ControlCreate.as_view(), name='control_create'),
    url(r'control/detail/(?P<pk>[0-9]+)/$', views.ControlDetail.as_view(), name='control_detail'),
    url(r'control/edit/(?P<pk>[0-9]+)/$', views.ControlUpdate.as_view(), name='control_update'),
    url(r'control/(?P<pk>[0-9]+)/delete/$', views.ControlDelete.as_view(), name='control_delete'),

]

sedc/variable/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from sensor.models import Sensor
from estacion.models import Estacion
from django.urls import reverse


# Create your models here.
class Unidad(models.Model):
    uni_id=models.AutoField("Id",primary_key=True)
    uni_nombre=models.CharField("Nombre",max_length=50)
    uni_sigla=models.CharField("Sigla",max_length=10)
    def __str__(self):
        return self.uni_nombre.encode('utf-8')
    def get_absolute_url(self):
        return reverse('variable:unidad_detail', kwargs={'pk': self.pk})
    class Meta:
        ordering=['uni_id']

class Variable(models.Model):
    var_id=models.AutoField("Id",primary_key=True)
    uni_id=models.ForeignKey(
    	Unidad,
    	models.SET_NULL,
    	blank=True,
    	null=True,
    	verbose_name="Unidad")
    var_codigo=models.CharField("Codigo",max_length=6)
    var_nombre=models.CharField("Nombre",max_length=50)
    var_maximo=models.DecimalField("Maximo",max_digits=7,decimal_places=2)
    var_minimo=models.DecimalField("Minimo",max_digits=7,decimal_places=2)
    var_sos=models.DecimalField("Sospechoso",max_digits=7,decimal_places=2,null=True,blank=True)
    var_err=models.DecimalField("Error",max_digits=7,decimal_places=2,null=True,blank=True)
    var_min=models.DecimalField("Error minimo",max_digits=7,decimal_places=2,null=True,blank=True)
    var_estado=models.BooleanField("Estado",default=True)
    def __str__(self):
        return self.var_nombre.encode('utf-8')
    def get_absolute_url(self):
        return reverse('variable:variable_detail', kwargs={'pk': self.pk})
    class Meta:
        ordering=['var_id']


class Control(models.Model):
    con_id=models.AutoField("Id",primary_key=True)
    var_id=models.ForeignKey(
    	Variable,
    	models.SET_NULL,
    	blank=True,
    	null=True,
    	verbose_name="Variable")
    sen_id=models.ForeignKey(
    	Sensor,
    	models.SET_NULL,
    	blank=True,
    	null=True,
    	verbose_name="Sensor")
    est_id=models.ForeignKey(
    	Estacion,
    	models.SET_NULL,
    	blank=True,
    	null=True,
    	verbose_name="Estación")
    con_fecha_ini=models.DateField("Fecha inicio")
    con_fecha_fin=models.DateField("Fecha fin",blank=True,null=True)
    con_estado=models.BooleanField("Activo",default=True)
    def get_absolute_url(self):
        return reverse('variable:control_detail', kwargs={'pk': self.pk})
    class Meta:
        ordering=['est_id_id']

sedc/variable/forms.py
# -*- coding: utf-8 -*-

from django import forms
from variable.models import Control
from estacion.models import Estacion
from formato.models import Variable
#from sensor.models import Sensor

class ControlSearchForm(forms.Form):
    var_id=forms.ModelChoiceField(label="Variable",required=False,
        queryset=Variable.objects.all())
    est_id=forms.ModelChoiceField(label="Estacion",required=False,
        queryset=Variable.objects.all())
    def filtrar(self,form):
        var_id=form.cleaned_data['var_id']
        est_id=form.cleaned_data['est_id']
        if var_id and est_id:
            lista=Control.objects.filter(
                var_id=var_id
            ).filter(
                est_id=est_id
            )
        elif var_id is None and est_id:
            lista=Control.objects.filter(
                est_id=est_id
            )
        elif est_id is None and var_id:
            lista=Control.objects.filter(
                var_id=var_id
            )
        else:
            lista=Control.objects.all()
        return lista

sedc/variable/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from .models import Variable, Unidad, Control
from django.views.generic import ListView, FormView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from .forms import ControlSearchForm
from django.contrib.auth.mixins import LoginRequiredMixin

#Variable views
class VariableCreate(LoginRequiredMixin,CreateView):
    model=Variable
    fields = ['var_codigo','var_nombre','uni_id','var_maximo','var_minimo','var_sos','var_err','var_min']
    def form_valid(self, form):
        return super(VariableCreate, self).form_valid(form)
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(VariableCreate, self).get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['title'] = "Crear"
        return context

class VariableList(LoginRequiredMixin,ListView):
    model=Variable
    paginate_by = 100
    def get_context_data(self, **kwargs):
        context = super(VariableList, self).get_context_data(**kwargs)
    	lista=Variable.objects.all()
        page=self.request.GET.get('page')
    	context.update(pagination(self.object_list,page,10))
        return context

class VariableDetail(LoginRequiredMixin,DetailView):
    model=Variable

class VariableUpdate(LoginRequiredMixin,UpdateView):
    model=Variable
    fields = ['var_codigo','var_nombre','uni_id','var_maximo','var_minimo','var_sos','var_err','var_min']
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(VariableUpdate, self).get_context_data(**kwargs)
        context['title'] = "Modificar"
        return context

class VariableDelete(LoginRequiredMixin,DeleteView):
    model=Variable
    success_url = reverse_lazy('variable:variable_index')

#Unidad
class UnidadCreate(LoginRequiredMixin,CreateView):
    model=Unidad
    fields = ['uni_nombre','uni_sigla']
    def form_valid(self, form):
        return super(UnidadCreate, self).form_valid(form)
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(UnidadCreate, self).get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['title'] = "Crear"
        return context

class UnidadList(LoginRequiredMixin,ListView):
    model=Unidad
    paginate_by = 10
    def get_context_data(self, **kwargs):
        context = super(UnidadList, self).get_context_data(**kwargs)
    	lista=Unidad.objects.all()
        page=self.request.GET.get('page')
    	context.update(pagination(self.object_list,page,10))
        return context

class UnidadDetail(LoginRequiredMixin,DetailView):
    model=Unidad

class UnidadUpdate(LoginRequiredMixin,UpdateView):
    model=Unidad
    fields = ['uni_nombre','uni_sigla']
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(UnidadUpdate, self).get_context_data(**kwargs)
        context['title'] = "Modificar"
        return context

class UnidadDelete(LoginRequiredMixin,DeleteView):
    model=Unidad
    success_url = reverse_lazy('variable:unidad_index')

#Model Control
class ControlCreate(LoginRequiredMixin,CreateView):
    model=Control
    #fields = ['var_id','est_id','con_fecha_ini','con_fecha_fin','con_estado']
    fields = ['var_id', 'sen_id', 'est_id', 'con_fecha_ini', 'con_fecha_fin', 'con_estado']
    def form_valid(self, form):
        return super(ControlCreate, self).form_valid(form)
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(ControlCreate, self).get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['title'] = "Crear"
        return context

class ControlList(LoginRequiredMixin,ListView,FormView):
    #parámetros ListView
    model=Control
    paginate_by=10
    #parámetros FormView
    template_name='variable/control_list.html'
    form_class=ControlSearchForm
    def post(self, request, *args, **kwargs):
        form=ControlSearchForm(self.request.POST or None)
        page=kwargs.get('page')
        if form.is_valid():
            self.object_list=form.filtrar(form)
        else:
            self.object_list=Control.objects.all()
        context = super(ControlList, self).get_context_data(**kwargs)
        context.update(pagination(self.object_list,page,10))
        return render(request,'variable/control_table.html',context)
    def get_context_data(self, **kwargs):
        context = super(ControlList, self).get_context_data(**kwargs)
        page=self.request.GET.get('page')
        context.update(pagination(self.object_list,page,10))
        return context

class ControlDetail(LoginRequiredMixin,DetailView):
    model=Control

class ControlUpdate(LoginRequiredMixin,UpdateView):
    model=Control
    fields = ['var_id','sen_id','est_id','con_fecha_ini','con_fecha_fin','con_estado']
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(ControlUpdate, self).get_context_data(**kwargs)
        context['title'] = "Modificar"
        return context

class ControlDelete(LoginRequiredMixin,DeleteView):
    model=Control
    success_url = reverse_lazy('variable:control_index')

def pagination(lista,page,num_reg):
    #lista=model.objects.all()
    paginator = Paginator(lista, num_reg)
    if page is None:
        page=1
    else:
        page=int(page)
    if page == 1:
        start=1
        last=start+1
    elif page == paginator.num_pages:
        last=paginator.num_pages
        start=last-1
    else:
        start=page-1
        last=page+1
    context={
        'first':'1',
        'last':paginator.num_pages,
        'range':range(start,last+1),
    }
    return context

sedc/templates/variable/control_confirm_delete.html
{% extends "index.html" %}
{% block content %}
{% load bootstrap3 %}
<h1><small>Borrar instalación</small></h1>
<div class="row">
  <div class="col-lg-4">
    <br>
    <table class="table table-striped table-bordered">
      <tr>
        <th>Variable</th>
        <td>{{control.var_id}}</td>
      </tr>
      <tr>
        <th>Sensor</th>
        <td>{{control.sen_id}}</td>
      </tr>
      <tr>
        <th>Estación</th>
        <td>{{control.est_id}}</td>
      </tr
      <tr>
        <th>Fecha inicio</th>
        <td>{{control.con_fecha_ini|date:"d/m/Y"}}</td>
      </tr>
      <tr>
        <th>Fecha fin</th>
        <td>{{control.con_fecha_fin|date:"d/m/Y"}}</td>
      </tr>
      <tr>
        <th>Estado</th>
        <td>{{control.con_estado}}</td>
      </tr>
    </table>
  </div>
</div>
<div class="row">
  <div class="col-lg-8">
    <form method="post" class="form">
      {% csrf_token %}
      <button type="submit" class="btn btn-default btn-warning">Confirmar</button>
      <a class="btn btn-default" href="{% url 'variable:control_index' %}">Cancelar</a>
    </form>
  </div>
</div>

{% endblock %}

sedc/templates/variable/control_detail.html
{% extends "index.html" %}

{% block content %}

{% load bootstrap3 %}

<div class="row">
  <div class="col-lg-4">
    <h1><small>Detalle de instalación</small></h1>
    <br>
    <table class="table table-striped table-bordered">
      <tr>
        <th>Variable</th>
        <td>{{control.var_id}}</td>
      </tr>
      <tr>
        <th>Sensor</th>
        <td>{{control.sen_id}}</td>
      </tr>
      <tr>
        <th>Estación</th>
        <td>{{control.est_id}}</td>
      </tr
      <tr>
        <th>Fecha inicio</th>
        <td>{{control.con_fecha_ini|date:"d/m/Y"}}</td>
      </tr>
      <tr>
        <th>Fecha fin</th>
        <td>{{control.con_fecha_fin|date:"d/m/Y"}}</td>
      </tr>
      <tr>
        <th>Estado</th>
        <td>{{control.con_estado}}</td>
      </tr>

    </table>
  </div>
</div>
<div class="row">
  <div class="col-lg-8">
    <a class="btn btn-primary" href="{% url 'variable:control_update' control.con_id %}">Modificar</a>
    <a class="btn btn-warning" href="{% url 'variable:control_delete' control.con_id%}">Borrar</a>
    <a class="btn btn-default" href="{% url 'variable:control_index' %}">Regresar</a>
  </div>
</div>

{% endblock %}

sedc/templates/variable/control_table.html
<script>
$(document).ready(function() {
  $(".link_page").click(function(e){
    e.preventDefault();
    actualizar_lista($(this).attr('href'));
  });
});
</script>
{% if object_list%}
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Variable</th>
      <th>Sensor</th>
      <th>Estación</th>
      <th>Fecha inicio</th>
      <th>Fecha fin</th>
    </tr>
  </thead>
  <tbody>
    {% for item in object_list %}
    <tr>
      <td>{{ item.var_id}}</td>
      <td>{{ item.sen_id}}</td>
      <td>{{ item.est_id}}</td>
      <td>{{ item.con_fecha_ini|date:"d/m/Y"}}</td>
      <td>{{ item.con_fecha_fin|date:"d/m/Y"}}</td>
      <td>
        <a href="{% url 'variable:control_detail' item.con_id %}">
          <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
        </a>
        <a href="{% url 'variable:control_update' item.con_id %}">
          <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
        </a>
        <a href="{% url 'variable:control_delete' item.con_id %}">
          <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
        </a>
      </td>
    </tr>

    {% endfor%}

  </tbody>
</table>
{% else %}
<div class="panel-body">
  <div class="alert alert-warning" role="alert">
    No existe información para la consulta
  </div>
</div>

{% endif %}


{% if is_paginated %}
<nav aria-label="Page navigation" style="float:right">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li><a class="link_page" href="{% url 'variable:control_index' first %}">&lt;&lt;</a></li>
    <li><a class="link_page" href="{% url 'variable:control_index' page_obj.previous_page_number %}">&lt;</a></li>
    {% else %}
    <li class="disabled"><span>&lt;</span></li>
    <li class="disabled"><span>&lt;&lt;</span></li>
    {% endif %}

    {% for i in range %}
    {% if page_obj.number == i %}
    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
    {% else %}
    <li><a class="link_page" href="{% url 'variable:control_index' i %}">{{ i }}</a></li>
    {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
    <li><a class="link_page" href="{% url 'variable:control_index' page_obj.next_page_number %}">&gt;</a></li>
    <li><a class="link_page" href="{% url 'variable:control_index' last %}">&gt;&gt;</a></li>
    {% else %}
    <li class="disabled"><span>&gt;</span></li>
    <li class="disabled"><span>&gt;&gt;</span></li>
    {% endif %}
  </ul>
</nav>
{% endif %}

sedc/templates/variable/unidad_detail.html
{% extends "index.html" %}

{% block content %}

{% load bootstrap3 %}

<div class="row">
  <div class="col-lg-4">
    <h1><small>Detalle de unidad</small></h1>
    <br>
    <table class="table table-striped table-bordered">
      <tr>
        <th>Nombre</th>
        <td>{{unidad.uni_nombre}}</td>
      </tr>
      <tr>
        <th>Sigla</th>
        <td>{{unidad.uni_sigla}}</td>
      </tr>

    </table>
  </div>
</div>
<div class="row">
  <div class="col-lg-8">
    <a class="btn btn-primary" href="{% url 'variable:unidad_update' unidad.uni_id %}">Modificar</a>
    <a class="btn btn-warning" href="{% url 'variable:unidad_delete' unidad.uni_id%}">Borrar</a>
    <a class="btn btn-default" href="{% url 'variable:unidad_index' %}">Regresar</a>
  </div>
</div>

{% endblock %}

sedc/templates/variable/unidad_list.html
{% extends "index.html" %}
{% block content %}
{% load bootstrap3 %}

<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">
    <div class="row">
      <div class="col-lg-9">
        <h4>Lista de Unidades</h4>
      </div>
      <div class="col-lg-3">
        <a style="float:right" class="btn btn-info"
        href="{% url 'variable:unidad_create' %}">
        Nuevo</a>
      </div>
    </div>
  </div><!-- end div class="panel-heading"-->

  <div class="panel-body">

  </div> <!-- end div class="panel-body"-->
  <table class="table table-striped table-bordered table-condensed">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Sigla</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for item in object_list %}
      <tr>
        <td>{{ item.uni_nombre}}</td>
        <td>{{ item.uni_sigla}}</td>
        <td>
          <a href="{% url 'variable:unidad_detail' item.uni_id %}">
            <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
          </a>
          <a href="{% url 'variable:unidad_update' item.uni_id %}">
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
          </a>
          <a href="{% url 'variable:unidad_delete' item.uni_id %}">
            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
          </a>
        </td>
      </tr>

      {% endfor%}

    </tbody>
  </table>

  {% if is_paginated %}
  <nav aria-label="Page navigation" style="float:right">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
      <li><a href="?page={{ first }}">&lt;&lt;</a></li>
      <li><a href="?page={{ page_obj.previous_page_number }}">&lt;</a></li>
      {% else %}
      <li class="disabled"><span>&lt;</span></li>
      <li class="disabled"><span>&lt;&lt;</span></li>
      {% endif %}

      {% for i in range %}
      {% if page_obj.number == i %}
      <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
      <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&gt;</a></li>
      <li><a href="?page={{ last }}">&gt;&gt;</a></li>
      {% else %}
      <li class="disabled"><span>&gt;</span></li>
      <li class="disabled"><span>&gt;&gt;</span></li>
      {% endif %}
    </ul>
  </nav>
  {% endif %}

</div><!--end div class="panel panel-default"-->

{% endblock %}

sedc/templates/variable/variable_detail.html
{% extends "index.html" %}

{% block content %}

{% load bootstrap3 %}

<div class="row">
  <div class="col-lg-4">
    <h1><small>Detalle de variable</small></h1>
    <br>
    <table class="table table-striped table-bordered">

      <tr>
        <th>Código</th>
        <td>{{variable.var_codigo}}</td>
      </tr>
      <tr>
        <th>Nombre</th>
        <td>{{variable.var_nombre}}</td>
      </tr>
      <tr>
        <th>Unidad</th>
        <td>{{variable.uni_id}}</td>
      </tr>
      <tr>
        <th>Máximo</th>
        <td>{{variable.var_maximo}}</td>
      </tr>
      <tr>
        <th>Mínimo</th>
        <td>{{variable.var_minimo}}</td>
      </tr>
      <tr>
        <th>Sos</th>
        <td>{{variable.var_sos}}</td>
      </tr>
      <tr>
        <th>Error</th>
        <td>{{variable.var_err}}</td>
      </tr>
      <tr>
        <th>Error mínimo</th>
        <td>{{variable.var_min}}</td>
      </tr>

    </table>
  </div>
</div>
<div class="row">
  <div class="col-lg-8">
    <a class="btn btn-primary" href="{% url 'variable:variable_update' variable.var_id %}">Modificar</a>
    <a class="btn btn-warning" href="{% url 'variable:variable_delete' variable.var_id%}">Borrar</a>
    <a class="btn btn-default" href="{% url 'variable:variable_index' %}">Regresar</a>
  </div>
</div>

{% endblock %}

sedc/templates/variable/variable_list.html
{% extends "index.html" %}
{% block content %}
{% load bootstrap3 %}

<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">
    <div class="row">
      <div class="col-lg-9">
        <h4>Lista de Variables</h4>
      </div>
      <div class="col-lg-3">
        <a style="float:right" class="btn btn-info"
        href="{% url 'variable:variable_create' %}">
        Nuevo</a>
      </div>
    </div>
  </div>

  <div class="panel-body">
    <table class="table table-striped table-bordered table-condensed">
      <thead>
        <tr>
          <th>Código</th>
          <th>Nombre</th>
          <th>Unidad</th>
          <th>Máximo</th>
          <th>Mínimo</th>
          <th>Valor sospechoso</th>
          <th>Valor erroneo</th>
          <th>Error mínimo (Variabilidad)</th>
        </tr>
      </thead>
      <tbody>
        {% for item in object_list %}
        <tr>
          <td>{{ item.var_codigo}}</td>
          <td>{{ item.var_nombre}}</td>
          <td>{{ item.uni_id}}</td>
          <td>{{ item.var_maximo}}</td>
          <td>{{ item.var_minimo}}</td>
          <td>{{ item.var_sos}}</td>
          <td>{{ item.var_err}}</td>
          <td>{{ item.var_min}}</td>
          <td>
            <a href="{% url 'variable:variable_detail' item.var_id %}">
              <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
            </a>
            <a href="{% url 'variable:variable_update' item.var_id %}">
              <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            </a>
            <a href="{% url 'variable:variable_delete' item.var_id %}">
              <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
            </a>
          </td>
        </tr>

        {% endfor%}

      </tbody>
    </table>

    {% if is_paginated %}
    <nav aria-label="Page navigation" style="float:right">
      <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li><a href="?page={{ first }}">&lt;&lt;</a></li>
        <li><a href="?page={{ page_obj.previous_page_number }}">&lt;</a></li>
        {% else %}
        <li class="disabled"><span>&lt;</span></li>
        <li class="disabled"><span>&lt;&lt;</span></li>
        {% endif %}

        {% for i in range %}
        {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
        {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}">&gt;</a></li>
        <li><a href="?page={{ last }}">&gt;&gt;</a></li>
        {% else %}
        <li class="disabled"><span>&gt;</span></li>
        <li class="disabled"><span>&gt;&gt;</span></li>
        {% endif %}
      </ul>
    </nav>
    {% endif %}
  </div>
  {% endblock %}