sedc/estacion/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns=[
    url(r'estacion/$',views.EstacionList.as_view(),name='estacion_index'),
    url(r'estacion/(?P<page>[0-9]+)/$',views.EstacionList.as_view(),name='estacion_index'),
    url(r'estacion/create/$', views.EstacionCreate.as_view(), name='estacion_create'),
    url(r'estacion/detail/(?P<pk>[0-9]+)/$', views.EstacionDetail.as_view(), name='estacion_detail'),
    url(r'estacion/edit/(?P<pk>[0-9]+)/$', views.EstacionUpdate.as_view(), name='estacion_update'),
    url(r'estacion/(?P<pk>[0-9]+)/delete/$', views.EstacionDelete.as_view(), name='estacion_delete'),

]

sedc/home/urls.py
from django.conf.urls import url
from django.urls import reverse_lazy
from home.views import HomePageView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import(
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

urlpatterns = [
    url(r'^$', HomePageView.as_view(), name='home'),
    #url(r'^$', LoginView.as_view(), name='login'),
    url(r'^login/$', LoginView.as_view(template_name='home/login.html'), name='login'),
    url(r'^logout/$', LogoutView.as_view(next_page=reverse_lazy('login')), name='logout')
]

sedc/registro/urls.py
from django.conf.urls import url
from registro import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns=[
    url(r'logmedicion/$',views.LogMedicionList.as_view(),name='logmedicion_index'),
    url(r'logmedicion/(?P<page>[0-9]+)/$',views.LogMedicionList.as_view(),name='logmedicion_index'),
    url(r'logmedicion/detail/(?P<pk>[0-9]+)/$', views.LogMedicionDetail.as_view(), name='logmedicion_detail'),

]

sedc/sedc/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #url(r'^$', TemplateView.as_view(template_name="home.html")),
    url(r'^',include('home.urls',namespace='home')),
    url(r'^',include('reportes.urls',namespace='reportes')),
    url(r'^',include('datalogger.urls',namespace='datalogger')),
    url(r'^',include('estacion.urls',namespace='estacion')),
    url(r'^',include('variable.urls',namespace='variable')),
    url(r'^',include('formato.urls',namespace='formato')),
    url(r'^',include('medicion.urls',namespace='medicion')),
    url(r'^',include('vacios.urls',namespace='vacios')),
    url(r'^',include('frecuencia.urls',namespace='frecuencia')),
    url(r'^',include('importacion.urls',namespace='importacion')),
    url(r'^',include('marca.urls',namespace='marca')),
    url(r'^',include('validacion.urls',namespace='validacion')),
    url(r'^',include('anuarios.urls',namespace='anuarios')),
    url(r'^',include('sensor.urls',namespace='sensor')),
    url(r'^',include('instalacion.urls',namespace='instalacion')),
    url(r'^',include('bitacora.urls',namespace='bitacora')),
    url(r'^',include('cruce.urls',namespace='cruce')),
    url(r'^',include('registro.urls',namespace='registro')),
    url('^', include('django.contrib.auth.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sedc/vacios/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns=[
    url(r'vacios/$',views.VaciosList.as_view(),name='vacios_index'),
    url(r'vacios/(?P<page>[0-9]+)/$',views.VaciosList.as_view(),name='vacios_index'),
    url(r'vacios/create/$', views.VaciosCreate.as_view(), name='vacios_create'),
    url(r'vacios/detail/(?P<pk>[0-9]+)/$', views.VaciosDetail.as_view(), name='vacios_detail'),
    url(r'vacios/edit/(?P<pk>[0-9]+)/$', views.VaciosUpdate.as_view(), name='vacios_update'),
    url(r'vacios/(?P<pk>[0-9]+)/delete/$', views.VaciosDelete.as_view(), name='vacios_delete'),
]

sedc/estacion/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class Estacion(models.Model):
    TIPO_ESTACION=(
        ('M','Meteorológica'),
        ('P','Pluviométrica'),
        ('H','Hidrológica'),
        )
    est_id=models.AutoField("Id",primary_key=True)
    est_codigo=models.CharField("Código",max_length=10)
    est_nombre=models.CharField("Nombre",max_length=100)
    est_tipo=models.CharField("Tipo",max_length=25,choices=TIPO_ESTACION)
    est_estado=models.BooleanField("Activo",default=True)
    est_provincia=models.CharField("Provincia",max_length=50,null=True)
    est_latitud=models.DecimalField("Latitud",max_digits=10,decimal_places=2,null=True)
    est_longitud=models.DecimalField("Longitud",max_digits=10,decimal_places=2,null=True)
    est_altura=models.IntegerField("Altura",null=True,validators=[MaxValueValidator(6000), MinValueValidator(0)])
    est_ficha=models.FileField("Fichas",upload_to='documents/')
    def __str__(self):
        return self.est_codigo.encode('utf-8')
    def get_absolute_url(self):
        return reverse('estacion:estacion_detail', kwargs={'pk': self.pk})
    class Meta:
        ordering=('est_id',)

sedc/registro/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from variable.models import Variable
from estacion.models import Estacion
from marca.models import Marca
from django.contrib.auth.models import User
from django import forms
from django.forms import ModelForm

# Create your models here.
class LogMedicion(models.Model):
    log_id=models.AutoField("Id",primary_key=True)
    medicion=models.IntegerField("medicion")
    variable=models.ForeignKey(
    	Variable,
    	models.SET_NULL,
    	blank=True,
    	null=True,
    	verbose_name="Variable")
    estacion=models.ForeignKey(
    	Estacion,
    	models.SET_NULL,
    	blank=True,
    	null=True,
    	verbose_name="Estación")
    marca=models.ForeignKey(
        Marca,
        models.SET_NULL,
        blank=True,
        null=True,
        verbose_name="Marca Datalogger"
    )
    med_fecha=models.DateTimeField("Fecha",auto_now_add=True)
    med_valor=models.DecimalField("Valor",max_digits=14,decimal_places=6,blank=True,null=True)
    med_maximo=models.DecimalField("Máximo",max_digits=14,decimal_places=6,blank=True,null=True)
    med_minimo=models.DecimalField("Mínimo",max_digits=14,decimal_places=6,blank=True,null=True)
    usuario=models.ForeignKey(
        User,
        models.SET_NULL,
        blank=True,
        null=True,
        verbose_name="Usuario"
    )
    log_fecha=models.DateTimeField("Fecha",auto_now=True)
    log_accion=models.CharField("Acción",max_length=200)
    log_mensaje=models.TextField("Mensaje")
    class Meta:
        ordering=('log_fecha',)
class LogMedicionSearchForm(forms.Form):
    estacion = forms.ModelChoiceField(required=False,
        queryset=Estacion.objects.order_by('est_id').all(),label='Estación')
    variable = forms.ModelChoiceField(required=False,
        queryset=Variable.objects.order_by('var_id').all(),label='Variable')
    lista=[]
    def filtrar(self,data):
        if isinstance(data,LogMedicionSearchForm):
            variable=data.cleaned_data['variable']
            estacion=data.cleaned_data['estacion']
        else:
            if data.get('var_id')== 'None':
                variable=None
            else:
                variable=Variable.objects.get(var_id=int(data.get('var_id')))
            if data.get('est_id')== 'None':
                estacion=None
            else:
                estacion=Estacion.objects.get(est_id=int(data.get('est_id')))
        if variable and estacion:
            lista=LogMedicion.objects.filter(
                variable=variable
            ).filter(
                estacion=estacion
            )
        elif variable is None and estacion:
            lista=LogMedicion.objects.filter(
                estacion=estacion
            )
        elif estacion is None and variable:
            lista=LogMedicion.objects.filter(
                variable=variable
            )
        else:
            lista=LogMedicion.objects.all()
        return lista

sedc/estacion/forms.py
# -*- coding: utf-8 -*-

from django import forms
#from uploads.core.models import Document
from estacion.models import Estacion

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Estacion
        fields = ('est_nombre', 'est_ficha', )

class EstacionSearchForm(forms.Form):
    TIPO_ESTACION=(
        ('','----'),
        ('M','Meteorológica'),
        ('P','Pluviométrica'),
        ('H','Hidrológica'),
        )

    lista=[]
    Tipo = forms.ChoiceField(required=False,choices=TIPO_ESTACION)
    Codigo = forms.CharField(required=False,max_length=10)

    def filtrar(self,form):
        if form.cleaned_data['Tipo'] and form.cleaned_data['Codigo']:
            lista=Estacion.objects.filter(
                est_tipo=form.cleaned_data['Tipo']
            ).filter(
                est_codigo=form.cleaned_data['Codigo']
            )
        elif form.cleaned_data['Tipo'] == "" and form.cleaned_data['Codigo']!="":
            lista=Estacion.objects.filter(
                est_codigo__icontains=form.cleaned_data['Codigo']
            )
        elif form.cleaned_data['Codigo'] == "" and form.cleaned_data['Tipo']!="":
            lista=Estacion.objects.filter(
                est_tipo=form.cleaned_data['Tipo']
            )
        else:
            lista=Estacion.objects.all()
        return lista

    def cadena(self,form):
        keys=form.cleaned_data.keys()
        string=str("?")
        i=1
        for item in keys:
            if i<len(keys):
                string+=item+"="+str(form.cleaned_data[item].encode('utf-8'))+"&"
            else:
                string+=item+"="+str(form.cleaned_data[item].encode('utf-8'))
            i+=1
        return string

sedc/estacion/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from .models import Estacion#, Registro
from django.views.generic import ListView, FormView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from .forms import EstacionSearchForm
from django.contrib.auth.mixins import LoginRequiredMixin
from home.functions import pagination

# Create your views here.
class EstacionCreate(LoginRequiredMixin,CreateView):
    model = Estacion
    fields = ['est_id', 'est_codigo','est_nombre','est_tipo','est_provincia','est_estado','est_latitud','est_longitud','est_altura','est_ficha']
    def form_valid(self, form):
        return super(EstacionCreate, self).form_valid(form)
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(EstacionCreate, self).get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['title'] = "Crear"
        print "context"
        return context
    def model_form_upload(request):
        if request.method == 'POST':
            form = DocumentForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                return redirect('index')
        else:
            form = DocumentForm()
        return render(request, 'core/model_form_upload.html', {
            'form': form
        })

class EstacionList(LoginRequiredMixin,ListView,FormView):
    #parámetros ListView
    model=Estacion
    paginate_by=10
    #parámetros FormView
    template_name='estacion/estacion_list.html'
    form_class=EstacionSearchForm
    def post(self, request, *args, **kwargs):
        form=EstacionSearchForm(self.request.POST or None)
        page=kwargs.get('page')
        if form.is_valid() and self.request.is_ajax:
            self.object_list=form.filtrar(form)
        else:
            self.object_list=Estacion.objects.all()
        context = super(EstacionList, self).get_context_data(**kwargs)
        context.update(pagination(self.object_list,page,10))
        return render(request,'estacion/estacion_table.html',context)
    def get_context_data(self, **kwargs):
        context = super(EstacionList, self).get_context_data(**kwargs)
        page=self.request.GET.get('page')
        context.update(pagination(self.object_list,page,10))
        return context

class EstacionDetail(LoginRequiredMixin,DetailView):
    model=Estacion
class EstacionUpdate(LoginRequiredMixin,UpdateView):
    model=Estacion
    fields = ['est_id', 'est_codigo','est_nombre','est_tipo','est_provincia','est_estado','est_latitud','est_longitud','est_altura','est_ficha']
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(EstacionUpdate, self).get_context_data(**kwargs)
        context['title'] = "Modificar"
        return context

class EstacionDelete(LoginRequiredMixin,DeleteView):
    model=Estacion
    success_url = reverse_lazy('estacion:estacion_index')

sedc/registro/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from registro.models import LogMedicion,LogMedicionSearchForm
from medicion.models import Medicion
from django.views.generic import ListView, FormView
from django.views.generic.detail import DetailView

from django.urls import reverse_lazy
from django.core.paginator import Paginator
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.

class LogMedicionList(LoginRequiredMixin,ListView,FormView):
    #parámetros ListView
    model=LogMedicion
    paginate_by=10
    #parámetros FormView
    template_name='registro/logmedicion_list.html'
    form_class=LogMedicionSearchForm
    #parametros propios
    def post(self, request, *args, **kwargs):
        form=LogMedicionSearchForm(self.request.POST or None)
        page=kwargs.get('page')
        if form.is_valid():
            self.object_list=form.filtrar(form)
            if self.request.is_ajax():
                context = super(LogMedicionList, self).get_context_data(**kwargs)
                page=kwargs.get('page')
                context.update(pagination(self.object_list,page,10))
                return render(request,'registro/logmedicion_table.html',context)
        else:
            self.object_list=LogMedicion.objects.all()
        #self.object_list=Estacion.objects.all()
        return self.render_to_response(self.get_context_data(form=form))

    def get_context_data(self, **kwargs):
        context = super(LogMedicionList, self).get_context_data(**kwargs)
        page=kwargs.get('page')
        context.update(pagination(self.object_list,page,10))
        return context
class LogMedicionDetail(LoginRequiredMixin,DetailView):
    model=LogMedicion
    template_name='registro/logmedicion_detail.html'
    def get_context_data(self, **kwargs):
        context = super(LogMedicionDetail, self).get_context_data(**kwargs)
        informacion=consultar_medicion(self.object)
        context['medicion']=informacion
        return context
def pagination(lista,page,num_reg):
    #lista=model.objects.all()
    paginator = Paginator(lista, num_reg)
    if page is None:
        page=1
    else:
        page=int(page)
    if page == 1:
        start=1
        last=start+1
    elif page == paginator.num_pages:
        last=paginator.num_pages
        start=last-1
    else:
        start=page-1
        last=page+1
    context={
        'first':'1',
        'last':paginator.num_pages,
        'range':range(start,last+1),
    }
    return context
def consultar_medicion(logmedicion):
    #fecha_split=med_fecha.split("-")
    #variable=Variable.objects.get(var_id=var_id)
    year=logmedicion.med_fecha.strftime('%Y')
    var_cod=logmedicion.variable.var_codigo
    tabla=var_cod+'.m'+year
    sql='SELECT * FROM '+tabla+ ' WHERE '
    sql+='med_id='+str(logmedicion.medicion)
    consulta=list(Medicion.objects.raw(sql))
    print sql
    return consulta[0]

sedc/templates/estacion/estacion_detail.html
{% extends "index.html" %}

{% block content %}

{% load bootstrap3 %}

<div class="row">
  <div class="col-lg-4">
    <h1><small>Detalle de estación</small></h1>
    <br>
    <table class="table table-striped table-bordered">
      <tr>
        <th>Código</th>
        <td>{{estacion.est_codigo}}</td>
      </tr>
      <tr>
        <th>Nombre</th>
        <td>{{estacion.est_nombre}}</td>
      </tr>
      <tr>
        <th>Tipo</th>
        <td>{{estacion.est_tipo}}</td>
      </tr>
      <tr>
        <th>Estado</th>
        <td>{{estacion.est_estado}}</td>
      </tr>
      <tr>
        <th>Provincia</th>
        <td>{{estacion.est_provincia}}</td>
      </tr>
      <tr>
        <th>Latitud</th>
        <td>{{estacion.est_latitud}}</td>
      </tr>
      <tr>
        <th>Longitud</th>
        <td>{{estacion.est_longitud}}</td>
      </tr>
      <tr>
        <th>Altura</th>
        <td>{{estacion.est_altura}}</td>
      </tr>
      <tr>
        <th>Fichas</th>
        <td><a target="_blank" href="{{ estacion.est_ficha.url }}">Descargar</a></td>
      </tr>
    </table>
  </div>
</div>
<div class="row">
  <div class="col-lg-8">
    <a class="btn btn-primary" href="{% url 'estacion:estacion_update' estacion.est_id %}">Modificar</a>
    <a class="btn btn-warning" href="{% url 'estacion:estacion_delete' estacion.est_id%}">Borrar</a>
    <a class="btn btn-default" href="{% url 'estacion:estacion_index' %}">Regresar</a>
  </div>
</div>

{% endblock %}

sedc/templates/estacion/estacion_form.html
{% extends "index.html" %}
{% block content %}
{% load bootstrap3 %}

<div class="col-lg-8 col-md-8 col-sm-6">
  <div class="panel panel-default">
    <div class="panel-heading">{{title}} Estación</div>
      <div class="panel-body">
        <form method="post" class="form" enctype="multipart/form-data">
          {% csrf_token %}
          <div class = "row">
          <div class="col-lg-6 col-md-6 col-sm-12">
              {% bootstrap_form form exclude='est_ficha,est_altura,est_longitud,est_latitud' %}
          </div>
          <div class="col-lg-6 col-md-6 col-sm-12">
              {% bootstrap_form form exclude='est_provincia,est_estado,est_tipo,est_nombre,est_codigo'%}
          </div>
          </div>

          <button type="submit" class="btn btn-default btn-primary">
            Guardar
          </button>
          <a class="btn btn-default"
          href="{% url 'estacion:estacion_index' %}">
          Cancelar</a>
        </form>
      </div>
  </div>
</div>

{% endblock %}

sedc/templates/estacion/estacion_table.html
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
$(document).ready(function() {
  $(".link_page").click(function(e){
    e.preventDefault();
    actualizar_lista($(this).attr('href'));
  });
  function actualizar_lista(enlace){
    $("#btn_filtrar").attr('disabled',true);
    $.ajax({
      url: enlace,
      data: $("#form_consulta").serialize(),
      type:'POST',
      beforeSend: function () {
        $("#div_informacion").hide();
        $("#div_loading").show();
        $("#div_error").hide();
      },
      success: function (data) {
        $("#div_informacion").show();
        $("#div_informacion").html(data)
        $("#div_loading").hide();
        $("#div_error").hide();
        $("#btn_filtrar").removeAttr('disabled');
      },
      error: function () {
        $("#div_loading").hide();
        $("#div_error").show();
        $("#btn_filtrar").removeAttr('disabled');
      }
    });
  }
});
</script>
<!-- Table -->
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Código</th>
      <th>Nombre</th>
      <th>Tipo</th>
      <th>Provincia</th>
      <th>Latitud</th>
      <th>Longitud</th>
      <th>Altura</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    {% for item in object_list %}
    <tr>
      <td>{{ item.est_codigo}}</td>
      <td>{{ item.est_nombre}}</td>
      <td>{{ item.est_tipo}}</td>
      <td>{{ item.est_provincia}}</td>
      <td>{{ item.est_latitud}}</td>
      <td>{{ item.est_longitud}}</td>
      <td>{{ item.est_altura}}</td>
      <td>
        <a href="{% url 'estacion:estacion_detail' item.est_id %}">
          <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
        </a>
        <a href="{% url 'estacion:estacion_update' item.est_id %}">
          <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
        </a>
        <a href="{% url 'estacion:estacion_delete' item.est_id %}">
          <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
        </a>
      </td>
    </tr>

    {% endfor%}

  </tbody>
</table>

{% if is_paginated %}
<nav aria-label="Page navigation" style="float:right">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li><a class="link_page" href="{% url 'estacion:estacion_index' first %}">&lt;&lt;</a></li>
    <li><a class="link_page" href="{% url 'estacion:estacion_index' page_obj.previous_page_number %}">&lt;</a></li>
    {% else %}
    <li class="disabled"><span>&lt;</span></li>
    <li class="disabled"><span>&lt;&lt;</span></li>
    {% endif %}

    {% for i in range %}
    {% if page_obj.number == i %}
    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
    {% else %}
    <li><a class="link_page" href="{% url 'estacion:estacion_index' i %}">{{ i }}</a></li>
    {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
    <li><a class="link_page" href="{% url 'estacion:estacion_index' page_obj.next_page_number %}">&gt;</a></li>
    <li><a class="link_page" href="{% url 'estacion:estacion_index' last %}">&gt;&gt;</a></li>
    {% else %}
    <li class="disabled"><span>&gt;</span></li>
    <li class="disabled"><span>&gt;&gt;</span></li>
    {% endif %}
  </ul>
</nav>
{% endif %}

sedc/templates/estacion/vacios_confirm_delete.html
{% extends "index.html" %}
{% block content %}
{% load bootstrap %}
<h1><small>Borrar vacios</small></h1>
<div class="row">
  <div class="col-lg-4">
    <br>
    <table class="table table-striped table-bordered">
      <tr>
        <th>Estación</th>
        <td>{{vacios.est_id}}</td>
      </tr>
      <tr>
        <th>Fecha inicio</th>
        <td>{{vacios.vac_fecha_ini}}</td>
      </tr>
      <tr>
        <th>Fecha fin</th>
        <td>{{vacios.vac_fecha_fin}}</td>
      </tr>
      <tr>
        <th>Observación</th>
        <td>{{vacios.vac_observacion}}</td>
      </tr>
    </table>
  </div>
</div>
<div class="row">
  <div class="col-lg-8">
    <form method="post" class="form">
      {% csrf_token %}
      <button type="submit" class="btn btn-default btn-warning">Confirmar</button>
      <a class="btn btn-default" href="{% url 'estacion:vacios_index' %}">Cancelar</a>
    </form>
  </div>
</div>

{% endblock %}

sedc/templates/estacion/vacios_detail.html
{% extends "index.html" %}

{% block content %}

{% load bootstrap %}

<div class="row">
  <div class="col-lg-4">
    <h1><small>Detalle de vacios</small></h1>
    <br>
    <table class="table table-striped table-bordered">
      <tr>
        <th>Estación</th>
        <td>{{vacios.est_id}}</td>
      </tr>
      <tr>
        <th>Fecha inicio</th>
        <td>{{vacios.vac_fecha_ini}}</td>
      </tr>
      <tr>
        <th>Fecha fin</th>
        <td>{{vacios.vac_fecha_fin}}</td>
      </tr>
      <tr>
        <th>Observación</th>
        <td>{{vacios.vac_observacion}}</td>
      </tr>
    </table>
  </div>
</div>
<div class="row">
  <div class="col-lg-8">
    <a class="btn btn-primary" href="{% url 'estacion:vacios_update' vacios.vac_id %}">Modificar</a>
    <a class="btn btn-warning" href="{% url 'estacion:vacios_delete' vacios.vac_id %}">Borrar</a>
    <a class="btn btn-default" href="{% url 'estacion:vacios_index' %}">Regresar</a>
  </div>
</div>

{% endblock %}

sedc/templates/estacion/vacios_list.html
{% extends "index.html" %}
{% block content %}
<div class="row">
  <div class="col-lg-10">
    <h3>Lista de vacios</h3>
  </div>
  <div class="col-lg-2" style="padding-top:20px;">
    <a style="float:right" class="btn btn-info"
    href="{% url 'estacion:vacios_create' %}">
    Nuevo</a>
  </div>
</div>
<br>
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Estación</th>
      <th>Fecha inicio</th>
      <th>Fecha fin</th>
      <th>Observación</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for item in object_list %}
    <tr>
      <td>{{ item.est_id }}</td>
      <td>{{ item.vac_fecha_ini }}</td>
      <td>{{ item.vac_fecha_fin }}</td>
      <td>{{ item.vac_observacion }}</td>
      <td>
        <a href="{% url 'estacion:vacios_detail' item.vac_id %}">
          <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
        </a>
        <a href="{% url 'estacion:vacios_update' item.vac_id %}">
          <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
        </a>
        <a href="{% url 'estacion:vacios_delete' item.vac_id %}">
          <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
        </a>
      </td>
    </tr>

    {% endfor%}

  </tbody>
</table>

{% if is_paginated %}
<nav aria-label="Page navigation" style="float:right">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li><a href="?page={{ first }}">&lt;&lt;</a></li>
    <li><a href="?page={{ page_obj.previous_page_number }}">&lt;</a></li>
    {% else %}
    <li class="disabled"><span>&lt;</span></li>
    <li class="disabled"><span>&lt;&lt;</span></li>
    {% endif %}

    {% for i in range %}
    {% if page_obj.number == i %}
    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
    {% else %}
    <li><a href="?page={{ i }}">{{ i }}</a></li>
    {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}">&gt;</a></li>
    <li><a href="?page={{ last }}">&gt;&gt;</a></li>
    {% else %}
    <li class="disabled"><span>&gt;</span></li>
    <li class="disabled"><span>&gt;&gt;</span></li>
    {% endif %}
  </ul>
</nav>
{% endif %}

{% endblock %}