sedc/bitacora/urls.py
from django.conf.urls import url
from bitacora import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns=[
    url(r'bitacora/$',views.BitacoraList.as_view(),name='bitacora_index'),
    url(r'bitacora/(?P<page>[0-9]+)/$',views.BitacoraList.as_view(),name='bitacora_index'),
    url(r'bitacora/create/$', views.BitacoraCreate.as_view(), name='bitacora_create'),
    url(r'bitacora/detail/(?P<pk>[0-9]+)/$', views.BitacoraDetail.as_view(), name='bitacora_detail'),
    url(r'bitacora/edit/(?P<pk>[0-9]+)/$', views.BitacoraUpdate.as_view(), name='bitacora_update'),
    url(r'bitacora/(?P<pk>[0-9]+)/delete/$', views.BitacoraDelete.as_view(), name='bitacora_delete'),

]

sedc/home/urls.py
from django.conf.urls import url
from django.urls import reverse_lazy
from home.views import HomePageView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import(
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

urlpatterns = [
    url(r'^$', HomePageView.as_view(), name='home'),
    #url(r'^$', LoginView.as_view(), name='login'),
    url(r'^login/$', LoginView.as_view(template_name='home/login.html'), name='login'),
    url(r'^logout/$', LogoutView.as_view(next_page=reverse_lazy('login')), name='logout')
]

sedc/sedc/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #url(r'^$', TemplateView.as_view(template_name="home.html")),
    url(r'^',include('home.urls',namespace='home')),
    url(r'^',include('reportes.urls',namespace='reportes')),
    url(r'^',include('datalogger.urls',namespace='datalogger')),
    url(r'^',include('estacion.urls',namespace='estacion')),
    url(r'^',include('variable.urls',namespace='variable')),
    url(r'^',include('formato.urls',namespace='formato')),
    url(r'^',include('medicion.urls',namespace='medicion')),
    url(r'^',include('vacios.urls',namespace='vacios')),
    url(r'^',include('frecuencia.urls',namespace='frecuencia')),
    url(r'^',include('importacion.urls',namespace='importacion')),
    url(r'^',include('marca.urls',namespace='marca')),
    url(r'^',include('validacion.urls',namespace='validacion')),
    url(r'^',include('anuarios.urls',namespace='anuarios')),
    url(r'^',include('sensor.urls',namespace='sensor')),
    url(r'^',include('instalacion.urls',namespace='instalacion')),
    url(r'^',include('bitacora.urls',namespace='bitacora')),
    url(r'^',include('cruce.urls',namespace='cruce')),
    url(r'^',include('registro.urls',namespace='registro')),
    url('^', include('django.contrib.auth.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sedc/bitacora/models.py
from __future__ import unicode_literals

from django.db import models
from variable.models import Variable
from estacion.models import Estacion
from django.urls import reverse
# Create your models here.
class Bitacora(models.Model):
    bit_id=models.AutoField("Id",primary_key=True)
    var_id=models.ForeignKey(
    	Variable,
    	models.SET_NULL,
    	blank=True,
    	null=True,
    	verbose_name="Variable")
    est_id=models.ForeignKey(
    	Estacion,
    	models.SET_NULL,
    	blank=True,
    	null=True,
    	verbose_name="Estacion")
    bit_fecha_ini=models.DateField("Fecha de inicio")
    bit_fecha_fin=models.DateField("fecha de fin",blank=True,null=True)
    bit_observacion=models.CharField("Observacion",max_length=500,blank=True)

    def __str__(self):
        return str(self.bit_id)
    def get_absolute_url(self):
        return reverse('bitacora:bitacora_index')
    class Meta:
        ordering=('bit_id','est_id','var_id',)

sedc/bitacora/forms.py
# -*- coding: utf-8 -*-

from django.forms import ModelForm
from bitacora.models import Bitacora
from estacion.models import Estacion
from variable.models import Variable


class BitacoraSearchForm(ModelForm):
    class Meta:
        model=Bitacora
        fields=['var_id','est_id']
    def filtrar(self,form):
        var_id=form.cleaned_data['var_id']
        est_id=form.cleaned_data['est_id']
        if var_id and est_id:
            lista=Bitacora.objects.filter(
                var_id=var_id
            ).filter(
                est_id=est_id
            )
        elif var_id  is None and est_id:
            lista=Bitacora.objects.filter(
                est_id=est_id
            )
        elif est_id is None and var_id:
            lista=Bitacora.objects.filter(
                var_id=var_id
            )
        else:
            lista=Bitacora.objects.all()
        return lista

    def cadena(self,form):
        keys=form.cleaned_data.keys()
        string=str("?")
        i=1
        for item in keys:
            if i<len(keys):
                string+=item+"="+str(form.cleaned_data[item])+"&"
            else:
                string+=item+"="+str(form.cleaned_data[item])
            i+=1
        return string

sedc/bitacora/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from bitacora.models import Bitacora
from django.views.generic import ListView, FormView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from bitacora.forms import BitacoraSearchForm
from django.contrib.auth.mixins import LoginRequiredMixin
#bitacora views
class BitacoraCreate(LoginRequiredMixin,CreateView):
    model=Bitacora
    fields = ['bit_id','est_id','var_id','bit_fecha_ini','bit_fecha_fin','bit_observacion']
    def form_valid(self, form):
        return super(BitacoraCreate, self).form_valid(form)
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(BitacoraCreate, self).get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['title'] = "Crear"
        return context

class BitacoraList(LoginRequiredMixin,ListView,FormView):
    model=Bitacora
    paginate_by = 10
    template_name='bitacora/bitacora_list.html'
    form_class=BitacoraSearchForm
    #parametros propios
    cadena=str("")
    def get(self, request, *args, **kwargs):
        form=BitacoraSearchForm(self.request.GET or None)
        self.object_list=Bitacora.objects.all()
        if form.is_valid():
            self.object_list=form.filtrar(form)
            self.cadena=form.cadena(form)
        return self.render_to_response(self.get_context_data(form=form))

    def get_context_data(self, **kwargs):
        context = super(BitacoraList, self).get_context_data(**kwargs)
        page=self.request.GET.get('page')
        print kwargs
        context.update(pagination(self.object_list,page,10))
        context["cadena"]=self.cadena
        return context

class BitacoraDetail(LoginRequiredMixin,DetailView):
    model=Bitacora

class BitacoraUpdate(LoginRequiredMixin,UpdateView):
    model=Bitacora
    fields = ['bit_id','est_id','var_id','bit_fecha_ini','bit_fecha_fin','bit_observacion']
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(BitacoraUpdate, self).get_context_data(**kwargs)
        context['title'] = "Modificar"
        return context

class BitacoraDelete(LoginRequiredMixin,DeleteView):
    model=Bitacora
    success_url = reverse_lazy('bitacora:bitacora_index')
def pagination(lista,page,num_reg):
    #lista=model.objects.all()
    paginator = Paginator(lista, num_reg)
    if page is None:
        page=1
    else:
        page=int(page)
    if page == 1:
        start=1
        last=start+1
    elif page == paginator.num_pages:
        last=paginator.num_pages
        start=last-1
    else:
        start=page-1
        last=page+1
    context={
        'first':'1',
        'last':paginator.num_pages,
        'range':range(start,last+1),
    }
    return context

sedc/templates/bitacora/bitacora_confirm_delete.html
{% extends "index.html" %}
{% block content %}
{% load bootstrap3 %}
<h1><small>Borrar bitacora</small></h1>
<div class="row">
  <div class="col-lg-4">
    <br>
    <table class="table table-striped table-bordered">
      <tr>
        <th>Estación</th>
        <td>{{bitacora.est_id}}</td>
      </tr>
      <tr>
        <th>Variable</th>
        <td>{{bitacora.var_id}}</td>
      </tr>
      <tr>
        <th>Fecha inicio</th>
        <td>{{bitacora.bit_fecha_ini|date:"d/m/Y"}}</td>
      </tr>
      <tr>
        <th>Fecha fin</th>
        <td>{{bitacora.bit_fecha_fin|date:"d/m/Y"}}</td>
      </tr>
      <tr>
        <th>Observacion</th>
        <td>{{bitacora.bit_observacion}}</td>
      </tr>
    </table>
  </div>
</div>
<div class="row">
  <div class="col-lg-8">
    <form method="post" class="form">
      {% csrf_token %}
      <button type="submit" class="btn btn-default btn-warning">Confirmar</button>
      <a class="btn btn-default" href="{% url 'bitacora:bitacora_index' %}">Cancelar</a>
    </form>
  </div>
</div>

{% endblock %}

sedc/templates/bitacora/bitacora_detail.html
{% extends "index.html" %}
{% block content %}
{% load bootstrap3 %}

<div class="row">
  <div class="col-lg-4">
    <h1><small>Bitacora</small></h1>
    <br>
    <table class="table table-striped table-bordered">
      <tr>
        <th>Estación</th>
        <td>{{bitacora.est_id}}</td>
      </tr>
      <tr>
        <th>Variable</th>
        <td>{{bitacora.var_id}}</td>
      </tr>
      <tr>
        <th>Fecha inicio</th>
        <td>{{bitacora.bit_fecha_ini|date:"d/m/Y"}}</td>
      </tr>
      <tr>
        <th>Fecha fin</th>
        <td>{{bitacora.bit_fecha_fin|date:"d/m/Y"}}</td>
      </tr>
      <tr>
        <th>Observacion</th>
        <td>{{bitacora.bit_observacion}}</td>
      </tr>
    </table>
  </div>
</div>
<div class="row">
  <div class="col-lg-8">
    <a class="btn btn-primary" href="{% url 'bitacora:bitacora_update' bitacora.bit_id %}">Modificar</a>
    <a class="btn btn-warning" href="{% url 'bitacora:bitacora_delete' bitacora.bit_id %}">Borrar</a>
    <a class="btn btn-default" href="{% url 'bitacora:bitacora_index' %}">Regresar</a>
  </div>
</div>

{% endblock %}

sedc/templates/bitacora/bitacora_form.html
{% extends "index.html" %}
{% block content %}
{% load bootstrap3 %}

<div class="col-lg-8 col-md-8 col-sm-6">
  <div class="panel panel-default">
    <div class="panel-heading">{{title}} Bitacora</div>
      <div class="panel-body">
        <form method="post" class="form">
          {% csrf_token %}
          <div class = "row">
          <div class="col-lg-6 col-md-6 col-sm-6">
              {% bootstrap_form form exclude='' %}
          </div>
          <div class="col-lg-6 col-md-6 col-sm-6">
              {% bootstrap_form form exclude='est_id,var_id,bit_fecha_ini,bit_fecha_fin,bit_observacion'%}
          </div>
          </div>

          <button type="submit" class="btn btn-default btn-primary">
            Guardar
          </button>
          <a class="btn btn-default"
          href="{% url 'bitacora:bitacora_index' %}">
          Cancelar</a>
        </form>
      </div>
  </div>
</div>

{% endblock %}

sedc/templates/bitacora/bitacora_list.html
{% extends "index.html" %}
{% block content %}
{% load bootstrap3 %}

<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">
    <div class="row">
      <div class="col-lg-9">
        <h4>Bitacora</h4>
      </div>
      <div class="col-lg-3">
        <a style="float:right" class="btn btn-info"
        href="{% url 'bitacora:bitacora_create' %}">
        Nueva Bitacora</a>
      </div>
    </div>
  </div>

<div class ="panel-body">
  <form class="form" method="get" action="{% url 'bitacora:bitacora_index'%}">
    {% for field in form%}
    {% bootstrap_field field form_group_class='col-lg-4' %}
    {% endfor %}
    <div class="form-group col-lg-4">
      <label>&nbsp;</label><br>
      <button type="submit" class="btn btn-default btn-primary">
        Buscar
      </button>
      <a class="btn btn-default"
      href="{% url 'bitacora:bitacora_index' %}">
      Limpiar</a>
    </div>
  </form>
</div>


<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Estacion</th>
      <th>Variable</th>
      <th>Fecha inicio</th>
      <th>Fecha fin</th>
      <th>Observacion</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for item in object_list %}
    <tr>
      <td>{{ item.est_id}}</td>
      <td>{{ item.var_id}}</td>
      <td>{{ item.bit_fecha_ini}}</td>
      <td>{{ item.bit_fecha_fin}}</td>
      <td>{{ item.bit_observacion}}</td>
      <td>
        <a href="{% url 'bitacora:bitacora_detail' item.bit_id %}">
          <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
        </a>
        <a href="{% url 'bitacora:bitacora_update' item.bit_id %}">
          <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
        </a>
        <a href="{% url 'bitacora:bitacora_delete' item.bit_id %}">
          <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
        </a>
      </td>
    </tr>

    {% endfor%}

  </tbody>
</table>

{% if is_paginated %}
<nav aria-label="Page navigation" style="float:right">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li><a href="?page={{ first }}">&lt;&lt;</a></li>
    <li><a href="?page={{ page_obj.previous_page_number }}">&lt;</a></li>
    {% else %}
    <li class="disabled"><span>&lt;</span></li>
    <li class="disabled"><span>&lt;&lt;</span></li>
    {% endif %}

    {% for i in paginator.page_range %}
    {% if page_obj.number == i %}
    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
    {% else %}
    <li><a href="{% url 'bitacora:bitacora_index' i%}">{{ i }}</a></li>
    {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}">&gt;</a></li>
    <li><a href="?page={{ last }}">&gt;&gt;</a></li>
    {% else %}
    <li class="disabled"><span>&gt;</span></li>
    <li class="disabled"><span>&gt;&gt;</span></li>
    {% endif %}
  </ul>
</nav>
{% endif %}
</div>

{% endblock %}