sedc/home/urls.py
from django.conf.urls import url
from django.urls import reverse_lazy
from home.views import HomePageView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import(
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

urlpatterns = [
    url(r'^$', HomePageView.as_view(), name='home'),
    #url(r'^$', LoginView.as_view(), name='login'),
    url(r'^login/$', LoginView.as_view(template_name='home/login.html'), name='login'),
    url(r'^logout/$', LogoutView.as_view(next_page=reverse_lazy('login')), name='logout')
]

sedc/medicion/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns=[
    url(r'^medicion/$',views.MedicionList.as_view(),name='medicion_index'),
    url(r'^medicion/listdelete/$',views.ListDelete.as_view(),name='list_delete'),
    url(r'^medicion/filter/$',views.MedicionFilter.as_view(),name='medicion_filter'),
    url(r'^medicion/filterdelete/$',views.FilterDelete.as_view(),name='filter_delete'),
    url(r'medicion/create/$', views.MedicionCreate.as_view(), name='medicion_create'),
    url(r'medicion/(?P<pk>[0-9]+)/(?P<fecha>[0-9-]+)/(?P<var_id>[0-9]+)/$', views.MedicionUpdate.as_view(), name='medicion_update'),
    url(r'medicion/delete/(?P<pk>[0-9]+)/(?P<fecha>[0-9-]+)/(?P<var_id>[0-9]+)/$', views.MedicionDelete.as_view(), name='medicion_delete'),
    url(r'medicion/importacion/(?P<imp_id>[0-9]+)/$',views.MedicionImportacion.as_view(),name='medicion_importacion'),
]

sedc/sedc/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #url(r'^$', TemplateView.as_view(template_name="home.html")),
    url(r'^',include('home.urls',namespace='home')),
    url(r'^',include('reportes.urls',namespace='reportes')),
    url(r'^',include('datalogger.urls',namespace='datalogger')),
    url(r'^',include('estacion.urls',namespace='estacion')),
    url(r'^',include('variable.urls',namespace='variable')),
    url(r'^',include('formato.urls',namespace='formato')),
    url(r'^',include('medicion.urls',namespace='medicion')),
    url(r'^',include('vacios.urls',namespace='vacios')),
    url(r'^',include('frecuencia.urls',namespace='frecuencia')),
    url(r'^',include('importacion.urls',namespace='importacion')),
    url(r'^',include('marca.urls',namespace='marca')),
    url(r'^',include('validacion.urls',namespace='validacion')),
    url(r'^',include('anuarios.urls',namespace='anuarios')),
    url(r'^',include('sensor.urls',namespace='sensor')),
    url(r'^',include('instalacion.urls',namespace='instalacion')),
    url(r'^',include('bitacora.urls',namespace='bitacora')),
    url(r'^',include('cruce.urls',namespace='cruce')),
    url(r'^',include('registro.urls',namespace='registro')),
    url('^', include('django.contrib.auth.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sedc/validacion/urls.py
from django.conf.urls import url
from validacion import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns=[
    url(r'^validacion/$',views.ValidacionList.as_view(),name='validacion_index'),
    url(r'validacion/create/$', views.ValidacionCreate.as_view(), name='validacion_create'),
    url(r'validacion/detail/(?P<pk>[0-9]+)/$', views.ValidacionDetail.as_view(), name='validacion_detail'),
    url(r'validacion/edit/(?P<pk>[0-9]+)/$', views.ValidacionUpdate.as_view(), name='validacion_update'),
    url(r'validacion/(?P<pk>[0-9]+)/delete/$', views.ValidacionDelete.as_view(), name='validacion_delete'),
    url(r'validacion/procesar/$', views.ProcesarValidacion.as_view(), name='procesar_validacion'),

]

sedc/medicion/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from variable.models import Variable
from estacion.models import Estacion
from marca.models import Marca
from django.urls import reverse
#clase para almacenar los datos crudos del sistema
class Medicion(models.Model):
    med_id=models.AutoField("Id",primary_key=True)
    var_id=models.ForeignKey(
    	Variable,
    	models.SET_NULL,
    	blank=True,
    	null=True,
    	verbose_name="Variable")
    est_id=models.ForeignKey(
    	Estacion,
    	models.SET_NULL,
    	blank=True,
    	null=True,
    	verbose_name="Estación")
    mar_id=models.ForeignKey(
        Marca,
        models.SET_NULL,
        blank=True,
        null=True,
        verbose_name="Marca Datalogger"
    )
    med_fecha=models.DateTimeField("Fecha")
    med_valor=models.DecimalField("Valor",max_digits=14,decimal_places=6,blank=True,null=True)
    med_maximo=models.DecimalField("Máximo",max_digits=14,decimal_places=6,blank=True,null=True)
    med_minimo=models.DecimalField("Mínimo",max_digits=14,decimal_places=6,blank=True,null=True)
    med_estado=models.NullBooleanField("Estado",default=True)
    def __str__(self):
        return str(self.med_fecha)
    def get_absolute_url(self):
        return reverse('medicion:medicion_index')
    class Meta:
        ordering=('med_fecha',)

sedc/medicion/forms.py
# -*- coding: utf-8 -*-
from django import forms
from estacion.models import Estacion
from variable.models import Variable
from medicion.models import Medicion
class MedicionSearchForm(forms.Form):
    TIPO_VARIABLE=(
        ('valor','valor'),
        ('maximo','maximo'),
        ('minimo','minimo'),
    )
    estacion=forms.ModelChoiceField(
        queryset=Estacion.objects.order_by('est_id').all())
    variable=forms.ModelChoiceField(
        queryset=Variable.objects.filter(var_id__in=[1,2,3,6,8]).order_by('var_id').all())
    inicio=forms.DateField(input_formats=['%d/%m/%Y'],label="Fecha de Inicio(dd/mm/yyyy)")
    fin=forms.DateField(input_formats=['%d/%m/%Y'],label="Fecha de Fin(dd/mm/yyyy)")
    valor=forms.ChoiceField(choices=TIPO_VARIABLE)
class FilterDeleteForm(forms.Form):
    estacion=forms.ModelChoiceField(
        queryset=Estacion.objects.order_by('est_id').all())
    variable=forms.ModelChoiceField(
        queryset=Variable.objects.order_by('var_id').all())
    fec_ini=forms.DateField(input_formats=['%d/%m/%Y'],label="Fecha de Inicio(dd/mm/yyyy)")
    hor_ini=forms.TimeField(input_formats=['%H:%M:%S'],label="Hora de Inicio(HH:MM:SS)")
    fec_fin=forms.DateField(input_formats=['%d/%m/%Y'],label="Fecha de Fin(dd/mm/yyyy)")
    hor_fin=forms.TimeField(input_formats=['%H:%M:%S'],label="Hora de Fin(HH:MM:SS)")

sedc/medicion/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from medicion.models import Medicion
from formato.models import Clasificacion
from importacion.models import Importacion
from django.views.generic import ListView,FormView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from medicion.forms import MedicionSearchForm,FilterDeleteForm
from medicion.functions import (filtrar,consultar,eliminar,
    consultar_objeto,modificar_medicion,eliminar_medicion,
    guardar_log,grafico)
from django.db import connection
from django.contrib.auth.mixins import LoginRequiredMixin
#Medicion views
class MedicionCreate(LoginRequiredMixin,CreateView):
    model=Medicion
    fields = ['var_id','est_id','med_fecha','med_valor','med_maximo',
              'med_minimo']
    def form_valid(self, form):
        return super(MedicionCreate, self).form_valid(form)
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(MedicionCreate, self).get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['title'] = "Crear"
        return context
#filtro para la validación de Datos Crudos
class MedicionFilter(LoginRequiredMixin,FormView):
    template_name='medicion/medicion_filter.html'
    form_class=MedicionSearchForm
    success_url='/medicion/filter/'
    lista=[]
    variable=""
    def post(self, request, *args, **kwargs):
        form=MedicionSearchForm(self.request.POST or None)
        if form.is_valid():
            if self.request.is_ajax():
                self.lista=filtrar(form)
                self.variable=form.cleaned_data['variable']
                return render(request,'medicion/medicion_list.html',
                    {'lista':self.lista,'variable':self.variable})
        return self.render_to_response(self.get_context_data(form=form))
    def get_context_data(self, **kwargs):
        context = super(MedicionFilter, self).get_context_data(**kwargs)
        context['lista']=self.lista
        context['variable']=self.variable
        return context
#Lista de datos crudos
class MedicionList(LoginRequiredMixin,FormView):
    template_name='medicion/medicion_list.html'
    form_class=MedicionSearchForm
    success_url='/medicion/'
    lista=[]
    variable=""
    def post(self, request, *args, **kwargs):
        form=MedicionSearchForm(self.request.POST or None)
        if form.is_valid():
            self.lista=filtrar(form)
            self.variable=form.cleaned_data['variable']
        return self.render_to_response(self.get_context_data(form=form))
    def get_context_data(self, **kwargs):
        context = super(MedicionList, self).get_context_data(**kwargs)
        context['lista']=self.lista
        context['variable']=self.variable
        return context
#Clase para filtrar datos para la vista delete
class ListDelete(LoginRequiredMixin,FormView,ListView):
    template_name='medicion/list_delete.html'
    form_class=FilterDeleteForm
    success_url='/medicion/listdelete/'
    model=Medicion
    variable=""
    def post(self, request, *args, **kwargs):
        form=FilterDeleteForm(self.request.POST or None)
        if form.is_valid():
            self.lista=consultar(form)
        return self.render_to_response(self.get_context_data(form=form))
    def get_context_data(self, **kwargs):
        context = super(ListDelete, self).get_context_data(**kwargs)
        context['lista']=self.lista
        return context



#filtro para eliminar los datos
class FilterDelete(LoginRequiredMixin,FormView):
    template_name='medicion/filter_delete.html'
    form_class=FilterDeleteForm
    success_url='/medicion/filterdelete/'
    #mensaje de confirmación
    mensaje=""
    def post(self,request,*args,**kwargs):
        form=FilterDeleteForm(self.request.POST or None)
        if form.is_valid():
            eliminar(form)
            self.mensaje="Datos Eliminados"
        return self.render_to_response(self.get_context_data(form=form))
    def get_context_data(self, **kwargs):
        context = super(FilterDelete, self).get_context_data(**kwargs)
        context['mensaje']=self.mensaje
        return context

class MedicionUpdate(LoginRequiredMixin,UpdateView):
    model=Medicion
    fields = ['med_valor','med_maximo','med_minimo']
    url=""
    def get(self, request, *args, **kwargs):
        #print kwargs.get('pk')
        med_id=kwargs.get('pk')
        med_fecha=kwargs.get('fecha')
        var_id=kwargs.get('var_id')
        self.object=consultar_objeto(kwargs)
        self.url="/medicion/"+med_id+"/"+med_fecha+"/"+var_id+"/"
        return self.render_to_response(self.get_context_data(**kwargs))
    def post(self, request, *args, **kwargs):
        modificar_medicion(kwargs,request.POST)
        self.object=consultar_objeto(kwargs)
        guardar_log(accion="Modificar",medicion=self.object,user=request.user)
        return self.render_to_response(self.get_context_data(**kwargs))
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(MedicionUpdate, self).get_context_data(**kwargs)
        context['url']=self.url
        return context

class MedicionDelete(LoginRequiredMixin,UpdateView):
    model=Medicion
    fields = ['est_id','var_id','med_fecha','med_valor','med_valor','med_maximo','med_minimo']
    url=""
    template_name='medicion/medicion_delete.html'
    def get(self, request, *args, **kwargs):
        med_id=kwargs.get('pk')
        med_fecha=kwargs.get('fecha')
        var_id=kwargs.get('var_id')
        self.object=consultar_objeto(kwargs)
        self.url="/medicion/delete/"+med_id+"/"+med_fecha+"/"+var_id+"/"
        return self.render_to_response(self.get_context_data(**kwargs))
    def post(self, request, *args, **kwargs):
        eliminar_medicion(kwargs,request.POST)
        self.object=consultar_objeto(kwargs)
        guardar_log(accion="Eliminar",medicion=self.object,user=request.user)
        return self.render_to_response(self.get_context_data(**kwargs))
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(MedicionDelete, self).get_context_data(**kwargs)
        context['url']=self.url
        return context

class MedicionImportacion(LoginRequiredMixin,FormView):
    model=Medicion
    template_name='medicion/medicion_importacion.html'
    form_class=MedicionSearchForm
    def get(self,request,*args,**kwargs):
        imp_id=kwargs.get('imp_id')
        importacion=Importacion.objects.get(imp_id=imp_id)
        clasificacion=Clasificacion.objects.filter(for_id=importacion.for_id)
        context=[]
        for fila in clasificacion:
            data={
                'estacion':importacion.est_id.est_id,
                'variable':fila.var_id.var_id,
                'inicio':importacion.imp_fecha_ini.strftime('%d/%m/%Y'),
                'fin':importacion.imp_fecha_fin.strftime('%d/%m/%Y')
            }
            form=MedicionSearchForm(data)
            if form.is_valid():
                #context[str(fila.var_id.var_codigo)]=consultar(form)
                consulta=consultar(form)
                obj_informacion=Informacion()
                obj_informacion.nombre=fila.var_id.var_nombre
                obj_informacion.lista=consulta
                obj_informacion.grafico=grafico(consulta,fila.var_id,importacion.est_id)
                context.append(obj_informacion)
            else:
                context=[]
        return self.render_to_response(self.get_context_data(informacion=context,form=form))
    def get_context_data(self, **kwargs):
        context = super(MedicionImportacion, self).get_context_data(**kwargs)
        return context
class Informacion():
    nombre=""
    lista=""
    grafico=""

sedc/templates/medicion/filter_delete.html
{% extends "index.html" %}
{% block content %}
{% load bootstrap3 %}
{% load humanize %}
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
// JQuery code to be added in here.
$( function() {
  $( "#id_inicio01" ).datepicker({
    changeMonth: true,
    changeYear: true,
    dateFormat:"dd/mm/yy"
  });
  $( "#id_fin01" ).datepicker({
    changeMonth: true,
    changeYear: true,
    dateFormat:"dd/mm/yy"
  });
  $("#btn_filtrar").click(function(){
    $("#btn_delete").attr('disabled',true);
    actualizar_lista();
    return false;
  });
});

function actualizar_lista(){


  $.ajax({
    url: '/medicion/listdelete/',
    type:'POST',
    data:$('#form_filter').serialize(),
    beforeSend: function(){
      $("#div_loading").show();
      $("#div_list").hide();
    },
    success: function (data) {
      $("#div_list").html(data)
      $("#div_list").show();
      $("#div_loading").hide();
      $("#btn_delete").removeAttr('disabled');
    }
  });
}
</script>
<div class="row">
  <div class="col-lg-10 col-sm-10">
    <h3>Eliminar Datos por Periodo</h3>
  </div>
</div>

<div class ="row">
  {% if mensaje %}
  <div class="alert alert-success" role="alert">
    {{mensaje}}
  </div>
  {% endif %}
  <form id="form_filter" class="form" method="post">
    {% csrf_token %}
    {% for field in form%}
    {% bootstrap_field field form_group_class='col-lg-6' %}
    {% endfor %}

    <div class="form-group col-lg-4">
      <label>&nbsp;</label><br>
      <button id="btn_filtrar" type="button" class="btn btn-default btn-primary">
        Buscar
      </button>
      <button id="btn_delete" disabled="disabled" type="submit" class="btn btn-default btn-primary">
        Eliminar
      </button>
      <a class="btn btn-default"
      href="{% url 'medicion:medicion_index' %}">
      Limpiar</a>
    </div>
  </form>
</div>
<br>
<div id="div_list" class="row">
</div>

<div id="div_loading" class="row" style="display:none;">
  <div class="col-lg-4 col-md-4 col-sm-4">&nbsp;</div>
  <div class="col-lg-4 col-md-4 col-sm-4">
    <img src="/media/loading6.gif" />
  </div>
  <div class="col-lg-4 col-md-4 col-sm-4">&nbsp;</div>
</div>
{% endblock %}

sedc/templates/medicion/list_delete.html
{% load bootstrap3 %}
{% load humanize %}

<div style="height:400px; overflow-x:hidden ; overflow-y: scroll; padding-bottom:10px;">
  <table class="table table-striped table-bordered table-condensed">
    <thead>
      <tr>
        <th>Fecha</th>
        <th>Hora</th>
        <th>Valor</th>
        <th>Máximo</th>
        <th>Mínimo</th>
      </tr>
    </thead>
    <tbody>
      {% for item in lista %}
      <tr>
        <td>{{ item.med_fecha|date:"d/m/Y"}}</td>
        <td>{{ item.med_hora|date:"H:i:s"}}</td>
        <td>{{ item.med_valor|floatformat:4 }}</td>
        <td>{{ item.med_maximo|floatformat:4 }}</td>
        <td>{{ item.med_minimo|floatformat:4 }}</td>
      </tr>

      {% endfor%}

    </tbody>
  </table>

</div>

sedc/templates/medicion/medicion_detail.html
{% extends "index.html" %}

{% block content %}

{% load bootstrap3 %}

<div class="row">
  <div class="col-lg-4">
    <h1><small>Detalle de medición</small></h1>
    <br>
    <table class="table table-striped table-bordered">
      <tr>
        <th>Variable</th>
        <td>{{medicion.var_id}}</td>
      </tr>
      <tr>
        <th>Estación</th>
        <td>{{medicion.est_id}}</td>
      </tr>
      <tr>
        <th>Fecha</th>
        <td>{{medicion.med_fecha|date:"d/m/Y"}}</td>
      </tr>
      <tr>
        <th>Hora</th>
        <td>{{medicion.med_hora|date:"H:i:s"}}</td>
      </tr>
      <tr>
        <th>Valor</th>
        <td>{{medicion.med_valor}}</td>
      </tr>
      <tr>
        <th>Máximo</th>
        <td>{{medicion.med_maximo}}</td>
      </tr>
      <tr>
        <th>Mínimo</th>
        <td>{{medicion.med_minimo}}</td>
      </tr>
      <tr>
        <th>Validado</th>
        <td>{{medicion.med_validado}}</td>
      </tr>
    </table>
  </div>
</div>
<div class="row">
  <div class="col-lg-8">
    <a class="btn btn-primary" href="{% url 'medicion:medicion_update' medicion.med_id %}">Modificar</a>
    <a class="btn btn-warning" href="{% url 'medicion:medicion_delete' medicion.med_id%}">Borrar</a>
    <a class="btn btn-default" href="{% url 'medicion:medicion_index' %}">Regresar</a>
  </div>
</div>

{% endblock %}

sedc/templates/medicion/medicion_filter.html
{% extends "index.html" %}
{% block content %}
{% load bootstrap3 %}
{% load humanize %}
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
// JQuery code to be added in here.
$( function() {
  $( "#id_inicio" ).datepicker({
    changeMonth: true,
    changeYear: true,
    dateFormat:"dd/mm/yy"
  });
  $( "#id_fin" ).datepicker({
    changeMonth: true,
    changeYear: true,
    dateFormat:"dd/mm/yy"
  });
  $("#btn_filtrar").click(function(){
    actualizar_lista();
    return false;
  });
  $( "#div_edit" ).dialog({
    autoOpen: false,
    width:400,
    height:350
  });
  $( "#div_delete" ).dialog({
    autoOpen: false,
    width:400,
    height:350
  });
});
function actualizar_lista(){
  $.ajax({
    url: '/medicion/filter/',
    data: $("#form_filter").serialize(),
    type:'POST',
    beforeSend: function () {
      activar_espera();
      $("#div_error").hide();
    },
    success: function (data) {
      $("#div_informacion").html(data)
      //$("#btn_procesar").removeAttr('disabled');
      desactivar_espera();
      //$("#div_mensaje").html("Datos Guardados")
      $("#div_error").hide();
    },
    error: function () {
      $("#div_informacion").hide();
      $("#div_loading").hide();
      $("#div_error").show();
      //$("#btn_procesar").removeAttr('disabled');
    }
  });

}
function activar_espera(){
  console.log('activar funcion')
  $("#div_loading").show();
  $("#div_informacion").hide();
}
function desactivar_espera(){
  console.log('desactivar funcion')
  $("#div_loading").hide();
  $("#div_informacion").show();
}
</script>
<div class="row">
  <div class="col-lg-10 col-sm-10">
    <h3>Validación Datos Crudos</h3>
  </div>
</div>

<div class ="row">
  <form id="form_filter" class="form" method="post">
    {% csrf_token %}
    {% for field in form%}
    {% bootstrap_field field form_group_class='col-lg-6' %}
    {% endfor %}
    <div class="form-group col-lg-4">
      <label>&nbsp;</label><br>
      <button id="btn_filtrar" type="button" class="btn btn-default btn-primary">
        Buscar
      </button>
      <a class="btn btn-default"
      href="{% url 'medicion:medicion_filter' %}">
      Limpiar</a>
    </div>
  </form>
</div>
<br>
<div id="div_informacion" class="row">

</div>
<div id="div_edit" title="Modificar Información">
</div>
<div id="div_delete" title="Eliminar Información">
</div>
<div id="div_loading" class="row" style="display:none;">
  <div class="col-lg-4 col-md-4 col-sm-4">&nbsp;</div>
  <div class="col-lg-4 col-md-4 col-sm-4">
    <img src="/media/loading6.gif" />
  </div>
  <div class="col-lg-4 col-md-4 col-sm-4">&nbsp;</div>
</div>
<div id="div_error" class="row" style="display:none;">
  <div class="alert alert-danger alert-dismissible" role="alert">
    Ocurrio un problema con el procesamiento de la información, por favor intentelo nuevamente
  </div>
</div>
{% endblock %}

sedc/templates/medicion/medicion_importacion.html
{% extends "index.html" %}
{% block content %}
{% load bootstrap3 %}
{% load humanize %}


{% for fila in informacion %}
<div class="row">
  <h4>{{fila.nombre}}</h4>
</div>
<div class="row">
  <div class="col-lg-6 col-md-12 col-sm-12" style="height:400px; overflow-x:hidden ; overflow-y: scroll; padding-bottom:10px;">
    <table class="table table-striped table-bordered table-condensed">
      <thead>
        <tr>
          <th>Fecha</th>
          <th>Hora</th>
          <th>Valor</th>
        </tr>
      </thead>
      <tbody>
        {% for item in fila.lista %}
        <tr>
          <td>{{ item.med_fecha|date:"d/m/Y"}}</td>
          <td>{{ item.med_fecha|date:"H:i:s"}}</td>
          <td>{{ item.med_valor}}</td>
        </tr>
        {% endfor%}
      </tbody>
    </table>
  </div>
  <div class="col-lg-6 col-md-12 col-sm-12" style="height:400px; overflow-x:hidden ; overflow-y: scroll; padding-bottom:10px;">
    {{fila.grafico|safe}}
  </div>


</div>

{% endfor %}
{% endblock %}

sedc/templates/medicion/validacion_list.html
{% extends "index.html" %}
{% block content %}
<div class="row">
  <div class="col-lg-10">
    <h3>Lista de validaciones</h3>
  </div>
  <div class="col-lg-2" style="padding-top:20px;">
    <a style="float:right" class="btn btn-info"
    href="{% url 'medicion:validacion_create' %}">
    Nuevo</a>
  </div>
</div>
<br>
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Medición</th>
      <th>Fecha</th>
      <th>Hora</th>
      <th>Valor</th>
      <th>Máximo</th>
      <th>Mínimo</th>
      <th>Mensaje</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for item in object_list %}
    <tr>
      <td>{{ item.med_id}}</td>
      <td>{{ item.val_fecha|date:"d/m/Y"}}</td>
      <td>{{ item.val_hora|date:"H:i:s"}}</td>
      <td>{{ item.val_valor}}</td>
      <td>{{ item.val_maximo}}</td>
      <td>{{ item.val_minimo}}</td>
      <td>{{ item.val_mensaje}}</td>
      <td>
        <a href="{% url 'medicion:validacion_detail' item.val_id %}">
          <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
        </a>
        <a href="{% url 'medicion:validacion_update' item.val_id %}">
          <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
        </a>
        <a href="{% url 'medicion:validacion_delete' item.val_id %}">
          <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
        </a>
      </td>
    </tr>

    {% endfor%}

  </tbody>
</table>

{% if is_paginated %}
<nav aria-label="Page navigation" style="float:right">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li><a href="?page={{ first }}">&lt;&lt;</a></li>
    <li><a href="?page={{ page_obj.previous_page_number }}">&lt;</a></li>
    {% else %}
    <li class="disabled"><span>&lt;</span></li>
    <li class="disabled"><span>&lt;&lt;</span></li>
    {% endif %}

    {% for i in range %}
    {% if page_obj.number == i %}
    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
    {% else %}
    <li><a href="?page={{ i }}">{{ i }}</a></li>
    {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}">&gt;</a></li>
    <li><a href="?page={{ last }}">&gt;&gt;</a></li>
    {% else %}
    <li class="disabled"><span>&gt;</span></li>
    <li class="disabled"><span>&gt;&gt;</span></li>
    {% endif %}
  </ul>
</nav>
{% endif %}

{% endblock %}